name: ci

on:
  pull_request:
  push:
    branches:
      - master
    tags-ignore:
      - v.*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14.x
      - name: Download deps
        run: make bootstrap
      - name: Verify fmt
        run: make verify-fmt
      - name: Verify codegen
        run: make verify-codegen
      - name: Run unit tests
        run: make test
