name: ci

on:
  pull_request:
  push:
    branches:
      - master
    tags-ignore:
      - v.*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14.x
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/github.com/deislabs/smi-sdk-go
      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download deps
        run: cd /home/runner/work/smi-sdk-go/smi-sdk-go/go/src/github.com/deislabs/smi-sdk-go && make tidy
        env:
          GOPATH: /home/runner/work/smi-sdk-go/go
      - name: Verify fmt
        run: cd /home/runner/work/smi-sdk-go/smi-sdk-go/go/src/github.com/deislabs/smi-sdk-go && make verify-fmt
        env:
          GOPATH: /home/runner/work/smi-sdk-go/go
      - name: Verify codegen
        run: cd /home/runner/work/smi-sdk-go/smi-sdk-go/go/src/github.com/deislabs/smi-sdk-go && make verify-codegen
        env:
          GOPATH: /home/runner/work/smi-sdk-go/go
      - name: Run unit tests
        run: cd /home/runner/work/smi-sdk-go/smi-sdk-go/go/src/github.com/deislabs/smi-sdk-go && make test
